// =============================================================
// xMED Government Essential Free Drugs Model
// Directorate General of Health Services (DGHS) & EDCL Formulary
// Official Bangladesh National Essential Drugs List (NEDL)
// 100% Free of Cost at Government Hospitals & Community Clinics
// =============================================================

const GOVERNMENT_FREE_DRUGS = [
  // --- SECTION 1: EMERGENCY & CRITICAL RESUSCITATION DRUGS ---
  {
    id: 'BD-EDCL-EM-01',
    brand_name: 'EDCL Adrenaline 1mg/ml Injection',
    generic_name: 'Epinephrine (Adrenaline)',
    strength: '1mg/1ml (1:1000)',
    dosage_form: 'Injection (Ampoule)',
    category: 'Emergency & Critical Care',
    is_emergency: true,
    emergency_indication: 'Acute Anaphylaxis, Severe Angioedema, Ventricular Fibrillation & Cardiac Arrest Resuscitation',
    facility_tier: 'Upazila Health Complex (UHC) & District Hospital Emergency',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL), Dhaka',
    stock_status: 'Available in Emergency Ward',
    route_of_admin: 'IM / SC / IV Infusion'
  },
  {
    id: 'BD-EDCL-EM-02',
    brand_name: 'EDCL Atropine Sulfate 0.6mg/ml Injection',
    generic_name: 'Atropine Sulfate',
    strength: '0.6mg/ml',
    dosage_form: 'Injection (Ampoule)',
    category: 'Emergency & Critical Care',
    is_emergency: true,
    emergency_indication: 'Severe Symptomatic Sinus Bradycardia & Organophosphate Poisoning Antidote',
    facility_tier: 'Upazila Health Complex (UHC) & District Emergency',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'Available in Emergency Ward',
    route_of_admin: 'IV / IM Injection'
  },
  {
    id: 'BD-EDCL-EM-03',
    brand_name: 'EDCL Hydrocortisone 100mg Injection',
    generic_name: 'Hydrocortisone Sodium Succinate',
    strength: '100mg / Vial',
    dosage_form: 'Injection (Vial with Diluent)',
    category: 'Emergency & Critical Care',
    is_emergency: true,
    emergency_indication: 'Acute Adrenocortical Insufficiency, Status Asthmaticus & Severe Anaphylactic Shock',
    facility_tier: 'Upazila Health Complex (UHC) & District Hospital',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'Available in Emergency Ward',
    route_of_admin: 'IV Injection / Infusion'
  },
  {
    id: 'BD-EDCL-EM-04',
    brand_name: 'EDCL Dexamethasone 5mg/ml Injection',
    generic_name: 'Dexamethasone Sodium Phosphate',
    strength: '5mg/ml (2ml Ampoule)',
    dosage_form: 'Injection (Ampoule)',
    category: 'Emergency & Critical Care',
    is_emergency: true,
    emergency_indication: 'Severe Cerebral Edema, Acute Severe Croup, Shock & Inflammatory Crisis',
    facility_tier: 'Community Clinic, UHC & All Govt Hospitals',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'Available in Emergency Ward',
    route_of_admin: 'IV / IM Injection'
  },
  {
    id: 'BD-EDCL-EM-05',
    brand_name: 'EDCL Oral Rehydration Salts (ORS)',
    generic_name: 'WHO Low Osmolarity Oral Rehydration Formula',
    strength: 'Sodium Chloride, Potassium Chloride, Trisodium Citrate, Glucose',
    dosage_form: 'Powder for Solution (Packet for 500ml)',
    category: 'Gastrointestinal & Rehydration',
    is_emergency: true,
    emergency_indication: 'Acute Watery Diarrhea, Cholera Dehydration & Heat Stroke Fluid Replenishment',
    facility_tier: 'Community Clinic, UHC & All Govt Health Outposts',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'High Stock (Distributed Freely)',
    route_of_admin: 'Oral'
  },
  {
    id: 'BD-EDCL-EM-06',
    brand_name: 'EDCL Diazepam 10mg/2ml Injection',
    generic_name: 'Diazepam',
    strength: '10mg/2ml',
    dosage_form: 'Injection (Ampoule)',
    category: 'Emergency & Critical Care',
    is_emergency: true,
    emergency_indication: 'Status Epilepticus, Acute Prolonged Convulsions, Severe Muscle Spasm & Eclampsia Pre-treatment',
    facility_tier: 'Upazila Health Complex (UHC) & District Emergency',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'Available in Emergency Ward',
    route_of_admin: 'Slow IV / Rectal'
  },
  {
    id: 'BD-EDCL-EM-07',
    brand_name: 'EDCL Furosemide (Lasix) 20mg/2ml Injection',
    generic_name: 'Furosemide',
    strength: '20mg/2ml',
    dosage_form: 'Injection (Ampoule)',
    category: 'Cardiovascular & Diuretics',
    is_emergency: true,
    emergency_indication: 'Acute Pulmonary Edema, Congestive Cardiac Failure & Hypertensive Encephalopathy',
    facility_tier: 'Upazila Health Complex (UHC) & District Emergency',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'Available in Emergency Ward',
    route_of_admin: 'Slow IV Injection'
  },
  {
    id: 'BD-EDCL-EM-08',
    brand_name: 'EDCL Magnesium Sulfate 50% Injection',
    generic_name: 'Magnesium Sulfate Heptahydrate',
    strength: '50% (5g / 10ml Ampoule)',
    dosage_form: 'Injection (Ampoule)',
    category: 'Maternal & Child Health',
    is_emergency: true,
    emergency_indication: 'Prevention & Management of Seizures in Severe Pre-eclampsia & Eclampsia (Obstetric Emergency)',
    facility_tier: 'Upazila Health Complex (UHC) & District Maternity Unit',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'Available in Labor Ward',
    route_of_admin: 'Deep IM / IV Infusion'
  },
  {
    id: 'BD-EDCL-EM-09',
    brand_name: 'EDCL Oxytocin 10 IU Injection',
    generic_name: 'Oxytocin',
    strength: '10 IU/ml',
    dosage_form: 'Injection (Ampoule)',
    category: 'Maternal & Child Health',
    is_emergency: true,
    emergency_indication: 'Prevention and Treatment of Postpartum Hemorrhage (PPH) & Labor Induction',
    facility_tier: 'Community Clinic, UHC & All Delivery Rooms',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'Available in Labor Room',
    route_of_admin: 'IM / IV Infusion'
  },
  {
    id: 'BD-EDCL-EM-10',
    brand_name: 'EDCL Salbutamol Respirator Solution 5mg/ml',
    generic_name: 'Salbutamol Sulfate',
    strength: '5mg/ml (15ml Solution for Nebulization)',
    dosage_form: 'Nebulizer Solution',
    category: 'Respiratory',
    is_emergency: true,
    emergency_indication: 'Acute Severe Bronchospasm, Asthma Exacerbation & Acute Obstructive Pulmonary Disease',
    facility_tier: 'Upazila Health Complex (UHC) & District Emergency',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'Available in Emergency Ward',
    route_of_admin: 'Inhalation via Nebulizer'
  },
  {
    id: 'BD-EDCL-EM-11',
    brand_name: 'EDCL Tetanus Toxoid (TT) 0.5ml Injection',
    generic_name: 'Tetanus Toxoid Vaccine',
    strength: '0.5ml (Single Dose Ampoule)',
    dosage_form: 'Injection (Ampoule)',
    category: 'Emergency & Critical Care',
    is_emergency: true,
    emergency_indication: 'Emergency Wound Trauma Prophylaxis & Maternal Neonatal Tetanus Prevention',
    facility_tier: 'Community Clinic, UHC & All Outpatient Clinics',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Directorate General of Health Services (DGHS)',
    stock_status: 'Cold-Chain Stored & Available',
    route_of_admin: 'Intramuscular (IM)'
  },
  {
    id: 'BD-EDCL-EM-12',
    brand_name: 'EDCL Anti-Tetanus Serum (ATS) 1500 IU',
    generic_name: 'Tetanus Antitoxin (Equine)',
    strength: '1500 IU / Ampoule',
    dosage_form: 'Injection (Ampoule)',
    category: 'Emergency & Critical Care',
    is_emergency: true,
    emergency_indication: 'Emergency Passive Immunization for Contaminated or Crushed Road Accident Wounds',
    facility_tier: 'Upazila Health Complex (UHC) & District Emergency',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Institute of Public Health (IPH) / DGHS',
    stock_status: 'Available in Emergency Ward',
    route_of_admin: 'SC / IM'
  },
  {
    id: 'BD-EDCL-EM-13',
    brand_name: 'EDCL Normal Saline 0.9% Infusion',
    generic_name: 'Sodium Chloride 0.9% IV Infusion',
    strength: '0.9% w/v (500ml / 1000ml Bottle)',
    dosage_form: 'Intravenous Infusion',
    category: 'Emergency & Critical Care',
    is_emergency: true,
    emergency_indication: 'Hypovolemic Shock Resuscitation, Extracellular Fluid Loss & Emergency Vehicle Fluid',
    facility_tier: 'Upazila Health Complex (UHC) & District Hospital',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'High Stock (Available)',
    route_of_admin: 'Intravenous Infusion'
  },
  {
    id: 'BD-EDCL-EM-14',
    brand_name: 'EDCL Cholera Saline (Ringer’s Lactate) 1000ml',
    generic_name: 'Hartmann’s Solution / Ringer’s Lactate',
    strength: 'Sodium Lactate, Sodium Chloride, Potassium & Calcium',
    dosage_form: 'Intravenous Infusion (1000ml Bag)',
    category: 'Emergency & Critical Care',
    is_emergency: true,
    emergency_indication: 'Severe Acute Dehydration with Metabolic Acidosis (Severe Cholera, Trauma Shock)',
    facility_tier: 'Community Clinic, UHC & All Diarrhea Wards',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'High Stock (Available)',
    route_of_admin: 'Fast IV Infusion'
  },
  {
    id: 'BD-EDCL-EM-15',
    brand_name: 'EDCL Ceftriaxone 1g Injection',
    generic_name: 'Ceftriaxone Sodium',
    strength: '1g Powder for Injection + 10ml WFI',
    dosage_form: 'Injection (Vial)',
    category: 'Antibiotic',
    is_emergency: true,
    emergency_indication: 'Severe Systemic Sepsis, Acute Bacterial Meningitis, Peritonitis & Complicated Pneumonia',
    facility_tier: 'Upazila Health Complex (UHC) & District Hospital',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'Available in Emergency Ward',
    route_of_admin: 'Slow IV / IM'
  },
  {
    id: 'BD-EDCL-EM-16',
    brand_name: 'EDCL Insulin Regular (Human Recombinant) 100 IU/ml',
    generic_name: 'Human Insulin Regular (Short-Acting)',
    strength: '100 IU/ml (10ml Vial)',
    dosage_form: 'Injection (Vial)',
    category: 'Endocrine & Metabolic',
    is_emergency: true,
    emergency_indication: 'Diabetic Ketoacidosis (DKA), Hyperosmolar Hyperglycemic State & Severe Acute Hyperkalemia',
    facility_tier: 'Upazila Health Complex (UHC) & District Hospital',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'Refrigerated & Available',
    route_of_admin: 'IV Infusion / SC'
  },
  {
    id: 'BD-EDCL-EM-17',
    brand_name: 'EDCL Silver Sulfadiazine 1% Cream',
    generic_name: 'Silver Sulfadiazine',
    strength: '1% w/w (25g Tube)',
    dosage_form: 'Topical Cream',
    category: 'Emergency & Critical Care',
    is_emergency: true,
    emergency_indication: 'Emergency Burn Wound Dressing, Infection Prophylaxis in 2nd & 3rd Degree Burns',
    facility_tier: 'Community Clinic, UHC & All Govt Hospitals',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'Available in Dressing Room',
    route_of_admin: 'Topical Application'
  },
  {
    id: 'BD-EDCL-EM-18',
    brand_name: 'EDCL Glyceryl Trinitrate (GTN) 0.5mg',
    generic_name: 'Nitroglycerin (Glyceryl Trinitrate)',
    strength: '0.5mg Sublingual Tablet',
    dosage_form: 'Sublingual Tablet',
    category: 'Cardiovascular & Diuretics',
    is_emergency: true,
    emergency_indication: 'Acute Angina Pectoris Attack & Emergency Pain Relief in Myocardial Infarction',
    facility_tier: 'Upazila Health Complex (UHC) & District Hospital Emergency',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'Available in Emergency Ward',
    route_of_admin: 'Sublingual'
  },

  // --- SECTION 2: ESSENTIAL ANTIBIOTICS & ANTI-INFECTIVES ---
  {
    id: 'BD-EDCL-AB-01',
    brand_name: 'EDCL Amoxicillin 500mg Capsule',
    generic_name: 'Amoxicillin Trihydrate',
    strength: '500mg',
    dosage_form: 'Capsule',
    category: 'Antibiotic',
    is_emergency: false,
    emergency_indication: null,
    facility_tier: 'Community Clinic & All Govt Health Facilities',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'In Stock',
    route_of_admin: 'Oral'
  },
  {
    id: 'BD-EDCL-AB-02',
    brand_name: 'EDCL Amoxicillin 250mg Capsule',
    generic_name: 'Amoxicillin Trihydrate',
    strength: '250mg',
    dosage_form: 'Capsule',
    category: 'Antibiotic',
    is_emergency: false,
    emergency_indication: null,
    facility_tier: 'Community Clinic & All Govt Facilities',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'In Stock',
    route_of_admin: 'Oral'
  },
  {
    id: 'BD-EDCL-AB-03',
    brand_name: 'EDCL Amoxicillin 125mg/5ml Suspension',
    generic_name: 'Amoxicillin Trihydrate',
    strength: '125mg/5ml (100ml Dry Syrup)',
    dosage_form: 'Syrup / Dry Suspension',
    category: 'Antibiotic',
    is_emergency: false,
    emergency_indication: null,
    facility_tier: 'Community Clinic & Pediatric Outpatient',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'In Stock',
    route_of_admin: 'Oral'
  },
  {
    id: 'BD-EDCL-AB-04',
    brand_name: 'EDCL Ciprofloxacin 500mg Tablet',
    generic_name: 'Ciprofloxacin Hydrochloride',
    strength: '500mg',
    dosage_form: 'Tablet',
    category: 'Antibiotic',
    is_emergency: false,
    emergency_indication: null,
    facility_tier: 'Community Clinic, UHC & District Hospital',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'In Stock',
    route_of_admin: 'Oral'
  },
  {
    id: 'BD-EDCL-AB-05',
    brand_name: 'EDCL Cotrimoxazole 480mg Tablet',
    generic_name: 'Sulfamethoxazole 400mg + Trimethoprim 80mg',
    strength: '480mg (400mg + 80mg)',
    dosage_form: 'Tablet',
    category: 'Antibiotic',
    is_emergency: false,
    emergency_indication: null,
    facility_tier: 'Community Clinic & All Health Centers',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'In Stock',
    route_of_admin: 'Oral'
  },
  {
    id: 'BD-EDCL-AB-06',
    brand_name: 'EDCL Cotrimoxazole Suspension',
    generic_name: 'Sulfamethoxazole 200mg + Trimethoprim 40mg / 5ml',
    strength: '240mg / 5ml (60ml Bottle)',
    dosage_form: 'Syrup / Suspension',
    category: 'Antibiotic',
    is_emergency: false,
    emergency_indication: null,
    facility_tier: 'Community Clinic & All Health Centers',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'In Stock',
    route_of_admin: 'Oral'
  },
  {
    id: 'BD-EDCL-AB-07',
    brand_name: 'EDCL Azithromycin 500mg Tablet',
    generic_name: 'Azithromycin Dihydrate',
    strength: '500mg',
    dosage_form: 'Tablet',
    category: 'Antibiotic',
    is_emergency: false,
    emergency_indication: null,
    facility_tier: 'Upazila Health Complex (UHC) & District Hospital',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'In Stock',
    route_of_admin: 'Oral'
  },
  {
    id: 'BD-EDCL-AB-08',
    brand_name: 'EDCL Doxycycline 100mg Capsule',
    generic_name: 'Doxycycline Hyclate',
    strength: '100mg',
    dosage_form: 'Capsule',
    category: 'Antibiotic',
    is_emergency: false,
    emergency_indication: null,
    facility_tier: 'Upazila Health Complex (UHC) & District Hospital',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'In Stock',
    route_of_admin: 'Oral'
  },
  {
    id: 'BD-EDCL-AB-09',
    brand_name: 'EDCL Gentamicin 80mg/2ml Injection',
    generic_name: 'Gentamicin Sulfate',
    strength: '80mg/2ml',
    dosage_form: 'Injection (Ampoule)',
    category: 'Antibiotic',
    is_emergency: true,
    emergency_indication: 'Severe Neonatal Sepsis & Complicated Gram-Negative Systemic Infections',
    facility_tier: 'Upazila Health Complex (UHC) & District Hospital',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'Available in Wards',
    route_of_admin: 'IM / IV Infusion'
  },
  {
    id: 'BD-EDCL-AB-10',
    brand_name: 'EDCL Metronidazole 400mg Tablet',
    generic_name: 'Metronidazole',
    strength: '400mg',
    dosage_form: 'Tablet',
    category: 'Antibiotic',
    is_emergency: false,
    emergency_indication: null,
    facility_tier: 'Community Clinic & All Health Centers',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'In Stock',
    route_of_admin: 'Oral'
  },
  {
    id: 'BD-EDCL-AB-11',
    brand_name: 'EDCL Metronidazole 500mg IV Infusion',
    generic_name: 'Metronidazole 5mg/ml (100ml)',
    strength: '500mg / 100ml',
    dosage_form: 'Intravenous Infusion',
    category: 'Antibiotic',
    is_emergency: true,
    emergency_indication: 'Emergency Post-Surgical Anaerobic Sepsis, Intra-Abdominal Abscess & Peritonitis',
    facility_tier: 'Upazila Health Complex (UHC) & District Surgery Ward',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'Available in OT / Ward',
    route_of_admin: 'Slow IV Infusion'
  },

  // --- SECTION 3: ANALGESICS, ANTIPYRETICS & ANTI-INFLAMMATORY ---
  {
    id: 'BD-EDCL-AN-01',
    brand_name: 'EDCL Paracetamol 500mg Tablet',
    generic_name: 'Paracetamol (Acetaminophen)',
    strength: '500mg',
    dosage_form: 'Tablet',
    category: 'Analgesic & Antipyretic',
    is_emergency: false,
    emergency_indication: null,
    facility_tier: 'Community Clinic & All Govt Facilities',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'High Stock (Distributed Freely)',
    route_of_admin: 'Oral'
  },
  {
    id: 'BD-EDCL-AN-02',
    brand_name: 'EDCL Paracetamol 120mg/5ml Syrup',
    generic_name: 'Paracetamol (Acetaminophen)',
    strength: '120mg/5ml (60ml Bottle)',
    dosage_form: 'Syrup',
    category: 'Analgesic & Antipyretic',
    is_emergency: false,
    emergency_indication: null,
    facility_tier: 'Community Clinic & Pediatric Outpatient',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'In Stock',
    route_of_admin: 'Oral'
  },
  {
    id: 'BD-EDCL-AN-03',
    brand_name: 'EDCL Diclofenac Sodium 50mg Tablet',
    generic_name: 'Diclofenac Sodium',
    strength: '50mg',
    dosage_form: 'Enteric-Coated Tablet',
    category: 'Analgesic & Antipyretic',
    is_emergency: false,
    emergency_indication: null,
    facility_tier: 'Community Clinic & All Outpatient Clinics',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'In Stock',
    route_of_admin: 'Oral'
  },
  {
    id: 'BD-EDCL-AN-04',
    brand_name: 'EDCL Diclofenac Sodium 75mg/3ml Injection',
    generic_name: 'Diclofenac Sodium',
    strength: '75mg/3ml',
    dosage_form: 'Injection (Ampoule)',
    category: 'Analgesic & Antipyretic',
    is_emergency: true,
    emergency_indication: 'Severe Acute Renal Colic, Acute Biliary Pain & Post-Operative Pain Crisis',
    facility_tier: 'Upazila Health Complex (UHC) & District Hospital Emergency',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'Available in Emergency Ward',
    route_of_admin: 'Deep Intramuscular (IM)'
  },
  {
    id: 'BD-EDCL-AN-05',
    brand_name: 'EDCL Aspirin 75mg Gastro-Resistant',
    generic_name: 'Acetylsalicylic Acid (Aspirin)',
    strength: '75mg',
    dosage_form: 'Tablet',
    category: 'Cardiovascular & Diuretics',
    is_emergency: true,
    emergency_indication: 'Emergency Antiplatelet Loading in Acute Coronary Syndrome & Suspected Myocardial Infarction',
    facility_tier: 'Upazila Health Complex (UHC) & District Hospital',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'Available in Emergency Ward',
    route_of_admin: 'Oral (Chewed in Emergency)'
  },

  // --- SECTION 4: GASTROINTESTINAL & ACID PEPTIC MEDICINES ---
  {
    id: 'BD-EDCL-GI-01',
    brand_name: 'EDCL Antacid Compound Tablet',
    generic_name: 'Dried Aluminium Hydroxide 250mg + Magnesium Hydroxide 400mg',
    strength: 'Standard Chewable',
    dosage_form: 'Chewable Tablet',
    category: 'Gastrointestinal & Rehydration',
    is_emergency: false,
    emergency_indication: null,
    facility_tier: 'Community Clinic & All Health Centers',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'High Stock (Distributed Freely)',
    route_of_admin: 'Oral (Chewable)'
  },
  {
    id: 'BD-EDCL-GI-02',
    brand_name: 'EDCL Antacid Suspension 200ml',
    generic_name: 'Aluminium Hydroxide + Magnesium Hydroxide Gel',
    strength: '200ml Bottle',
    dosage_form: 'Liquid Suspension',
    category: 'Gastrointestinal & Rehydration',
    is_emergency: false,
    emergency_indication: null,
    facility_tier: 'Community Clinic & All Health Centers',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'In Stock',
    route_of_admin: 'Oral'
  },
  {
    id: 'BD-EDCL-GI-03',
    brand_name: 'EDCL Omeprazole 20mg Capsule',
    generic_name: 'Omeprazole',
    strength: '20mg',
    dosage_form: 'Capsule (Delayed Release)',
    category: 'Gastrointestinal & Rehydration',
    is_emergency: false,
    emergency_indication: null,
    facility_tier: 'Community Clinic, UHC & District Hospital',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'High Stock (Distributed Freely)',
    route_of_admin: 'Oral'
  },
  {
    id: 'BD-EDCL-GI-04',
    brand_name: 'EDCL Omeprazole 40mg IV Injection',
    generic_name: 'Omeprazole Sodium',
    strength: '40mg Vial with 10ml Solvent',
    dosage_form: 'Injection (Vial)',
    category: 'Gastrointestinal & Rehydration',
    is_emergency: true,
    emergency_indication: 'Acute Upper Gastrointestinal Hemorrhage (Bleeding Peptic Ulcer) & Stress Ulcer Prophylaxis',
    facility_tier: 'Upazila Health Complex (UHC) & District Hospital',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'Available in Emergency Ward',
    route_of_admin: 'Slow IV Injection'
  },

  // --- SECTION 5: RESPIRATORY & ANTIHISTAMINES ---
  {
    id: 'BD-EDCL-RS-01',
    brand_name: 'EDCL Salbutamol 4mg Tablet',
    generic_name: 'Salbutamol Sulfate',
    strength: '4mg',
    dosage_form: 'Tablet',
    category: 'Respiratory',
    is_emergency: false,
    emergency_indication: null,
    facility_tier: 'Community Clinic & All Outpatient Clinics',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'In Stock',
    route_of_admin: 'Oral'
  },
  {
    id: 'BD-EDCL-RS-02',
    brand_name: 'EDCL Salbutamol 2mg/5ml Syrup',
    generic_name: 'Salbutamol Sulfate',
    strength: '2mg/5ml (100ml Bottle)',
    dosage_form: 'Syrup',
    category: 'Respiratory',
    is_emergency: false,
    emergency_indication: null,
    facility_tier: 'Community Clinic & Pediatric Outpatient',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'In Stock',
    route_of_admin: 'Oral'
  },
  {
    id: 'BD-EDCL-RS-03',
    brand_name: 'EDCL Salbutamol 100mcg Evohaler',
    generic_name: 'Salbutamol Inhaler',
    strength: '100mcg per actuation (200 Puffs)',
    dosage_form: 'Metered Dose Inhaler (MDI)',
    category: 'Respiratory',
    is_emergency: true,
    emergency_indication: 'Immediate Relief of Acute Asthma Attacks & Reversible Airway Obstruction',
    facility_tier: 'Upazila Health Complex (UHC) & District Outpatient',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'In Stock',
    route_of_admin: 'Inhalation'
  },
  {
    id: 'BD-EDCL-RS-04',
    brand_name: 'EDCL Chlorpheniramine 4mg Tablet',
    generic_name: 'Chlorpheniramine Maleate (Piriton formula)',
    strength: '4mg',
    dosage_form: 'Tablet',
    category: 'Respiratory',
    is_emergency: false,
    emergency_indication: null,
    facility_tier: 'Community Clinic & All Health Centers',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'High Stock (Distributed Freely)',
    route_of_admin: 'Oral'
  },
  {
    id: 'BD-EDCL-RS-05',
    brand_name: 'EDCL Chlorpheniramine 2mg/5ml Syrup',
    generic_name: 'Chlorpheniramine Maleate',
    strength: '2mg/5ml (60ml Bottle)',
    dosage_form: 'Syrup',
    category: 'Respiratory',
    is_emergency: false,
    emergency_indication: null,
    facility_tier: 'Community Clinic & All Health Centers',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'In Stock',
    route_of_admin: 'Oral'
  },
  {
    id: 'BD-EDCL-RS-06',
    brand_name: 'EDCL Aminophylline 250mg/10ml Injection',
    generic_name: 'Aminophylline',
    strength: '250mg/10ml',
    dosage_form: 'Injection (Ampoule)',
    category: 'Respiratory',
    is_emergency: true,
    emergency_indication: 'Severe Acute Bronchospasm in Refractory Asthma & Pulmonary Edema',
    facility_tier: 'Upazila Health Complex (UHC) & District Hospital',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'Available in Emergency Ward',
    route_of_admin: 'Slow IV Infusion'
  },

  // --- SECTION 6: MATERNAL, REPRODUCTIVE & CHILD NUTRITION ---
  {
    id: 'BD-EDCL-MH-01',
    brand_name: 'EDCL Iron & Folic Acid Tablet',
    generic_name: 'Dried Ferrous Sulfate 200mg + Folic Acid 0.5mg',
    strength: '200mg + 0.5mg',
    dosage_form: 'Tablet',
    category: 'Maternal & Child Health',
    is_emergency: false,
    emergency_indication: null,
    facility_tier: 'Community Clinic & All Maternal Centers',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'High Stock (Free for Pregnant Mothers)',
    route_of_admin: 'Oral'
  },
  {
    id: 'BD-EDCL-MH-02',
    brand_name: 'EDCL Zinc Sulfate 20mg Dispersible',
    generic_name: 'Zinc Sulfate Monohydrate',
    strength: '20mg Elemental Zinc',
    dosage_form: 'Dispersible Tablet',
    category: 'Maternal & Child Health',
    is_emergency: false,
    emergency_indication: null,
    facility_tier: 'Community Clinic & All Health Centers',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'High Stock (Free for Pediatric Diarrhea)',
    route_of_admin: 'Oral (Dissolved in water / breastmilk)'
  },
  {
    id: 'BD-EDCL-MH-03',
    brand_name: 'DGHS Vitamin A Red Capsule 200,000 IU',
    generic_name: 'Retinol (Vitamin A)',
    strength: '200,000 IU',
    dosage_form: 'Softgel Capsule (Cut-and-squeeze)',
    category: 'Maternal & Child Health',
    is_emergency: false,
    emergency_indication: null,
    facility_tier: 'Community Clinic & National Immunization Days',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Directorate General of Health Services (DGHS)',
    stock_status: 'High Stock',
    route_of_admin: 'Oral'
  },
  {
    id: 'BD-EDCL-MH-04',
    brand_name: 'EDCL Albendazole 400mg Chewable',
    generic_name: 'Albendazole',
    strength: '400mg',
    dosage_form: 'Chewable Tablet',
    category: 'Anthelmintic & Nutrition',
    is_emergency: false,
    emergency_indication: null,
    facility_tier: 'Community Clinic & National Deworming Program',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'High Stock (Distributed Freely)',
    route_of_admin: 'Oral'
  },
  {
    id: 'BD-EDCL-MH-05',
    brand_name: 'EDCL Vitamin B-Complex Tablet',
    generic_name: 'Thiamine (B1) + Riboflavin (B2) + Pyridoxine (B6) + Nicotinamide',
    strength: 'Therapeutic Standard Formula',
    dosage_form: 'Sugar-Coated Tablet',
    category: 'Anthelmintic & Nutrition',
    is_emergency: false,
    emergency_indication: null,
    facility_tier: 'Community Clinic & All Health Centers',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'High Stock',
    route_of_admin: 'Oral'
  },
  {
    id: 'BD-EDCL-MH-06',
    brand_name: 'EDCL Calcium Carbonate 500mg + D3',
    generic_name: 'Calcium Carbonate 500mg + Cholecalciferol 200 IU',
    strength: '500mg + 200 IU',
    dosage_form: 'Tablet',
    category: 'Maternal & Child Health',
    is_emergency: false,
    emergency_indication: null,
    facility_tier: 'Community Clinic & Antenatal Outpatient',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'In Stock',
    route_of_admin: 'Oral'
  },

  // --- SECTION 7: CARDIOVASCULAR & ANTIHYPERTENSIVE ---
  {
    id: 'BD-EDCL-CV-01',
    brand_name: 'EDCL Amlodipine 5mg Tablet',
    generic_name: 'Amlodipine Besylate',
    strength: '5mg',
    dosage_form: 'Tablet',
    category: 'Cardiovascular & Diuretics',
    is_emergency: false,
    emergency_indication: null,
    facility_tier: 'Community Clinic, UHC & NCD Corners',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'High Stock (Govt NCD Program)',
    route_of_admin: 'Oral'
  },
  {
    id: 'BD-EDCL-CV-02',
    brand_name: 'EDCL Atenolol 50mg Tablet',
    generic_name: 'Atenolol',
    strength: '50mg',
    dosage_form: 'Tablet',
    category: 'Cardiovascular & Diuretics',
    is_emergency: false,
    emergency_indication: null,
    facility_tier: 'Upazila Health Complex (UHC) & District Outpatient',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'In Stock',
    route_of_admin: 'Oral'
  },
  {
    id: 'BD-EDCL-CV-03',
    brand_name: 'EDCL Hydrochlorothiazide 25mg',
    generic_name: 'Hydrochlorothiazide',
    strength: '25mg',
    dosage_form: 'Tablet',
    category: 'Cardiovascular & Diuretics',
    is_emergency: false,
    emergency_indication: null,
    facility_tier: 'Community Clinic & NCD Corners',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'In Stock',
    route_of_admin: 'Oral'
  },
  {
    id: 'BD-EDCL-CV-04',
    brand_name: 'EDCL Losartan Potassium 50mg',
    generic_name: 'Losartan Potassium',
    strength: '50mg',
    dosage_form: 'Tablet',
    category: 'Cardiovascular & Diuretics',
    is_emergency: false,
    emergency_indication: null,
    facility_tier: 'Upazila Health Complex (UHC) & NCD Corners',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'In Stock',
    route_of_admin: 'Oral'
  },

  // --- SECTION 8: ANTIDIABETIC MEDICATIONS ---
  {
    id: 'BD-EDCL-DM-01',
    brand_name: 'EDCL Metformin 500mg Tablet',
    generic_name: 'Metformin Hydrochloride',
    strength: '500mg',
    dosage_form: 'Tablet',
    category: 'Endocrine & Metabolic',
    is_emergency: false,
    emergency_indication: null,
    facility_tier: 'Community Clinic, UHC & NCD Corners',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'High Stock (Govt NCD Program)',
    route_of_admin: 'Oral'
  },
  {
    id: 'BD-EDCL-DM-02',
    brand_name: 'EDCL Glibenclamide 5mg Tablet',
    generic_name: 'Glibenclamide (Glyburide)',
    strength: '5mg',
    dosage_form: 'Tablet',
    category: 'Endocrine & Metabolic',
    is_emergency: false,
    emergency_indication: null,
    facility_tier: 'Upazila Health Complex (UHC) & NCD Corners',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'In Stock',
    route_of_admin: 'Oral'
  },

  // --- SECTION 9: OPHTHALMIC, TOPICAL & DERMATOLOGICAL ---
  {
    id: 'BD-EDCL-OP-01',
    brand_name: 'EDCL Gentamicin 0.3% Eye/Ear Drops',
    generic_name: 'Gentamicin Sulfate',
    strength: '0.3% w/v (5ml Dropper Bottle)',
    dosage_form: 'Ophthalmic / Otic Solution',
    category: 'Ophthalmic & Dermatological',
    is_emergency: false,
    emergency_indication: null,
    facility_tier: 'Community Clinic & All Health Centers',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'In Stock',
    route_of_admin: 'Ophthalmic / Otic'
  },
  {
    id: 'BD-EDCL-OP-02',
    brand_name: 'EDCL Ciprofloxacin 0.3% Eye Drops',
    generic_name: 'Ciprofloxacin Hydrochloride',
    strength: '0.3% (5ml Bottle)',
    dosage_form: 'Eye Drops',
    category: 'Ophthalmic & Dermatological',
    is_emergency: false,
    emergency_indication: null,
    facility_tier: 'Upazila Health Complex (UHC) & District Eye OPD',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'In Stock',
    route_of_admin: 'Ophthalmic'
  },
  {
    id: 'BD-EDCL-DM-03',
    brand_name: 'EDCL Povidone Iodine 10% Solution',
    generic_name: 'Povidone Iodine',
    strength: '10% w/v (100ml Bottle)',
    dosage_form: 'Topical Solution',
    category: 'Emergency & Critical Care',
    is_emergency: true,
    emergency_indication: 'Immediate Surgical Antisepsis, Trauma Disinfection & Contaminated Wound Cleaning',
    facility_tier: 'Community Clinic, UHC & All Dressing Rooms',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'High Stock (Available)',
    route_of_admin: 'Topical'
  },
  {
    id: 'BD-EDCL-DM-04',
    brand_name: 'EDCL Benzyl Benzoate 25% Application',
    generic_name: 'Benzyl Benzoate',
    strength: '25% w/v (100ml Bottle)',
    dosage_form: 'Topical Emulsion',
    category: 'Ophthalmic & Dermatological',
    is_emergency: false,
    emergency_indication: null,
    facility_tier: 'Community Clinic & All Health Centers',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'In Stock (Scabies Treatment)',
    route_of_admin: 'Topical'
  },
  {
    id: 'BD-EDCL-DM-05',
    brand_name: 'EDCL Clotrimazole 1% Cream',
    generic_name: 'Clotrimazole',
    strength: '1% w/w (15g Tube)',
    dosage_form: 'Topical Cream',
    category: 'Ophthalmic & Dermatological',
    is_emergency: false,
    emergency_indication: null,
    facility_tier: 'Community Clinic & All Health Centers',
    price: '৳0.00 (100% Free Govt Supply)',
    manufacturer: 'Essential Drugs Company Limited (EDCL)',
    stock_status: 'In Stock',
    route_of_admin: 'Topical'
  }
];

// --- Accessor & Search Methods ---

function getAllGovernmentDrugs(options = {}) {
  let list = [...GOVERNMENT_FREE_DRUGS];

  if (options.emergency_only) {
    list = list.filter(d => d.is_emergency === true);
  }

  if (options.category && options.category !== 'All') {
    list = list.filter(d => d.category.toLowerCase().includes(options.category.toLowerCase()));
  }

  if (options.search) {
    const q = options.search.toLowerCase().trim();
    list = list.filter(d => 
      d.brand_name.toLowerCase().includes(q) ||
      d.generic_name.toLowerCase().includes(q) ||
      d.category.toLowerCase().includes(q) ||
      (d.emergency_indication && d.emergency_indication.toLowerCase().includes(q))
    );
  }

  return list;
}

function getEmergencyDrugs() {
  return GOVERNMENT_FREE_DRUGS.filter(d => d.is_emergency === true);
}

function getDrugById(id) {
  return GOVERNMENT_FREE_DRUGS.find(d => d.id === id) || null;
}

function getDrugCategories() {
  const categories = new Set(GOVERNMENT_FREE_DRUGS.map(d => d.category));
  return ['All', ...Array.from(categories)];
}

module.exports = {
  GOVERNMENT_FREE_DRUGS,
  getAllGovernmentDrugs,
  getEmergencyDrugs,
  getDrugById,
  getDrugCategories
};
